### ISSUE TITLE
Questions About specific stuff

### ISSUE THREAD

**Issue by nonunknown** [go-p5/p5#46]
I tried run p5 while doing other stuff like this:

![image](https://user-images.githubusercontent.com/58845030/116079406-25757480-a66e-11eb-913f-9065137f51ea.png)
basically, in this situation the p5 window doesnt run, there's a way to run it, while listening to connections?

I tried running it in concurrency mode:
![image](https://user-images.githubusercontent.com/58845030/116079554-4dfd6e80-a66e-11eb-9a01-c2f0e0055d1a.png)
but didnt worked.

The Second question is: How to Run it on browser using gorilla?

**Comment by sbinet** [comment]
the `p5.Run` function is kind of a "high-level" API.
for the kind of things you seem to want to achieve, you'll probably have to drop to the `p5.Proc` API.

that said, `go-p5` is built on top of [Gio](https://gioui.org) which supports WASM.
so, instead of having `go-p5` run server-side (and then, somehow sending back the image to the client), one could compile the `p5.Run(setup, draw)` part to a WASM binary and serve that via `net/http` or `Gorilla` like any other JS resource.

**Comment by sbinet** [comment]
I've just added a simple example:
- https://github.com/go-p5/p5/pull/47

let me know.
